# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmN_vjHR7We2BUDNDSDaNQWDh11QJK6T

Link Dataset:

https://www.kaggle.com/datasets/harrywang/wine-dataset-for-clustering
"""

import glob
import os
import kagglehub
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import (
    AffinityPropagation,
    AgglomerativeClustering,
    DBSCAN,
    KMeans,
    SpectralClustering,
)
from sklearn.datasets import load_wine
from sklearn.decomposition import PCA
from sklearn.metrics import adjusted_rand_score, davies_bouldin_score, silhouette_score
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler

# 1. Download and preprocess the dataset
path = kagglehub.dataset_download("harrywang/wine-dataset-for-clustering")
csv_files = glob.glob(os.path.join(path, "*.csv"))
df = pd.read_csv(csv_files[0])

X = df.copy()
y_true = load_wine().target  # Ground truth labels (3 cultivars)

# Feature standardization
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 2D PCA projection for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
var_ratio = pca.explained_variance_ratio_ * 100

# 2. Train 6 clustering models
models = {
    "K-Means (k=3)": KMeans(n_clusters=3, random_state=42, n_init=10),
    "Agglomerative (k=3)": AgglomerativeClustering(n_clusters=3, linkage="ward"),
    "GMM (k=3)": GaussianMixture(n_components=3, random_state=42),
    "Spectral (k=3)": SpectralClustering(
        n_clusters=3, affinity="nearest_neighbors", random_state=42
    ),
    "DBSCAN (eps=2.3)": DBSCAN(eps=2.3, min_samples=4),
    "Affinity Propagation": AffinityPropagation(damping=0.8, random_state=42),
}

results = {}
for name, model in models.items():
    results[name] = model.fit_predict(X_scaled)

# 3. Compute evaluation metrics
metrics = []
for name, labels in results.items():
    mask = labels != -1
    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    noise_count = int(np.sum(labels == -1))

    sil = (
        silhouette_score(X_scaled[mask], labels[mask])
        if n_clusters > 1 and np.sum(mask) > n_clusters
        else np.nan
    )
    db = (
        davies_bouldin_score(X_scaled[mask], labels[mask])
        if n_clusters > 1 and np.sum(mask) > n_clusters
        else np.nan
    )
    ari = adjusted_rand_score(y_true, labels) if n_clusters > 0 else np.nan

    metrics.append({
        "Model": name,
        "Clusters": n_clusters,
        "Noise Points": noise_count,
        "Silhouette": round(sil, 4) if not np.isnan(sil) else "N/A",
        "Davies-Bouldin": round(db, 4) if not np.isnan(db) else "N/A",
        "ARI (vs True y)": round(ari, 4) if not np.isnan(ari) else "N/A",
    })

print("=== CLUSTERING PERFORMANCE COMPARISON (WINE DATASET) ===")
print(pd.DataFrame(metrics).to_string(index=False))

# 4. Visualization: 1 Ground Truth + 6 Clustering Algorithms (2x4 grid, 8th slot unused)
fig, axes = plt.subplots(2, 4, figsize=(22, 10))
axes = axes.flatten()

# Plot 0: Ground Truth
scatter_gt = axes[0].scatter(
    X_pca[:, 0],
    X_pca[:, 1],
    c=y_true,
    cmap="Set1",
    edgecolors="k",
    s=45,
    alpha=0.8,
)
axes[0].set_title("★ Ground Truth (3 Cultivars)", fontsize=11, fontweight="bold", color="darkred")
axes[0].set_xlabel(f"PC1 ({var_ratio[0]:.1f}%)")
axes[0].set_ylabel(f"PC2 ({var_ratio[1]:.1f}%)")
axes[0].grid(True, linestyle="--", alpha=0.3)

# Plots 1 - 6: Clustering Algorithms
for idx, (name, labels) in enumerate(results.items(), start=1):
    ax = axes[idx]
    unique_labels = sorted(list(set(labels)))
    colors = plt.cm.tab10(np.linspace(0, 1, max(len(unique_labels), 1)))

    for k in unique_labels:
        mask = labels == k
        if k == -1:
            color = [0.6, 0.6, 0.6, 0.5]
            label_text = "Noise"
        else:
            color = colors[k % 10]
            label_text = f"C{k}"

        ax.scatter(
            X_pca[mask, 0],
            X_pca[mask, 1],
            color=color,
            edgecolors="k",
            s=40,
            alpha=0.75,
            label=label_text if len(unique_labels) <= 4 else None,
        )

    ari_val = next(item["ARI (vs True y)"] for item in metrics if item["Model"] == name)
    ax.set_title(f"{name} (ARI: {ari_val})", fontsize=11, fontweight="bold")
    ax.set_xlabel(f"PC1 ({var_ratio[0]:.1f}%)")
    ax.set_ylabel(f"PC2 ({var_ratio[1]:.1f}%)")
    ax.grid(True, linestyle="--", alpha=0.3)
    if len(unique_labels) <= 4:
        ax.legend(loc="upper right", fontsize=8)

# Hide the unused 8th subplot
axes[7].axis("off")

plt.suptitle("Comparison of Ground Truth and 6 Clustering Algorithms (Wine Dataset)", fontsize=15, y=0.99)
plt.tight_layout()
plt.show()

"""# Clustering Analysis on the Wine Dataset

## 1. Dataset Overview
* **Source:** UCI Machine Learning Repository (`harrywang/wine-dataset-for-clustering` via Kaggle).
* **Sample Size:** 178 samples with 13 continuous chemical properties (Alcohol, Malic Acid, Flavanoids, Proline, etc.).
* **Target Objective:** Discover natural cluster groupings without prior labels. Ground truth comprises 3 distinct wine cultivars (`load_wine()` from `scikit-learn`).

---

## 2. Experimental Methodology
1. **Standardization:** Applied `StandardScaler` to ensure zero mean and unit variance across features with widely varying scales (e.g., Proline vs. Flavanoids).
2. **Dimensionality Reduction:** Computed 2D PCA for visual benchmarking across models.
3. **Clustering Models Evaluated:**
   * **Distance-based:** K-Means ($k=3$)
   * **Hierarchical:** Agglomerative Clustering ($k=3$, Ward linkage)
   * **Probabilistic:** Gaussian Mixture Models ($k=3$, Full Covariance)
   * **Graph-based:** Spectral Clustering ($k=3$, Nearest Neighbors)
   * **Density-based:** DBSCAN ($\epsilon=2.3$, $\text{min\_samples}=4$)
   * **Exemplar-based:** Affinity Propagation ($\text{damping}=0.8$)

---

## 3. Performance & Evaluation

| Algorithm | Clusters Found | Noise Points | ARI (vs. Ground Truth) | Silhouette Score | Davies-Bouldin Index |
| :--- | :---: | :---: | :---: | :---: | :---: |
| **K-Means ($k=3$)** | 3 | 0 | **0.8975** | 0.2849 | 1.3892 |
| **GMM ($k=3$)** | 3 | 0 | **0.8975** | 0.2842 | 1.3905 |
| **Spectral ($k=3$)** | 3 | 0 | **0.8804** | 0.2780 | 1.4150 |
| **Agglomerative ($k=3$)** | 3 | 0 | **0.7899** | 0.2774 | 1.4187 |
| **DBSCAN ($\epsilon=2.3$)** | 2 | 41 | **0.4100** | 0.2115 | 1.6240 |
| **Affinity Propagation** | 15 | 0 | **0.2449** | 0.1199 | 1.6384 |

---

## 4. Key Findings & Insights
* **Top Performers (K-Means & GMM):** Standardized chemical properties naturally form three convex, globular clusters in high-dimensional space, yielding near-optimal partitions ($\text{ARI} \approx 0.8975$).
* **DBSCAN Limitation:** Lacks a strict density boundary between cultivars. A single global radius $\epsilon$ causes adjacent cultivars to merge while treating peripheral samples as noise.
* **Affinity Propagation Over-segmentation:** Without an explicit cluster count constraint, message-passing optimizes local exemplar similarities, splitting the 3 macroscopic cultivars into 15 micro-clusters.

Dataset Links:

https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
"""

import glob
import os
import kagglehub
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import (
    AffinityPropagation,
    AgglomerativeClustering,
    DBSCAN,
    KMeans,
    SpectralClustering,
)
from sklearn.decomposition import PCA
from sklearn.metrics import adjusted_rand_score, davies_bouldin_score, silhouette_score
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler

# 1. Download and preprocess the dataset
path = kagglehub.dataset_download("uciml/breast-cancer-wisconsin-data")
csv_files = glob.glob(os.path.join(path, "*.csv"))
df = pd.read_csv(csv_files[0])

# Drop irrelevant/unnamed columns
cols_to_drop = [col for col in ['id', 'Unnamed: 32'] if col in df.columns]
df = df.drop(columns=cols_to_drop)

# Extract ground truth labels (0: Benign, 1: Malignant) and features
y_true = df['diagnosis'].map({'B': 0, 'M': 1}).values
X = df.drop(columns=['diagnosis'])

# Feature standardization
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 2D PCA projection for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
var_ratio = pca.explained_variance_ratio_ * 100

# 2. Train 6 clustering models
models = {
    "K-Means (k=2)": KMeans(n_clusters=2, random_state=42, n_init=10),
    "Agglomerative (k=2)": AgglomerativeClustering(n_clusters=2, linkage="ward"),
    "GMM (k=2)": GaussianMixture(n_components=2, random_state=42),
    "Spectral (k=2)": SpectralClustering(
        n_clusters=2, affinity="nearest_neighbors", random_state=42
    ),
    "DBSCAN (eps=4.5)": DBSCAN(eps=4.5, min_samples=5),
    "Affinity Propagation": AffinityPropagation(damping=0.9, preference=-150, random_state=42),
}

results = {}
for name, model in models.items():
    results[name] = model.fit_predict(X_scaled)

# 3. Compute evaluation metrics
metrics = []
for name, labels in results.items():
    mask = labels != -1
    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    noise_count = int(np.sum(labels == -1))

    sil = (
        silhouette_score(X_scaled[mask], labels[mask])
        if n_clusters > 1 and np.sum(mask) > n_clusters
        else np.nan
    )
    db = (
        davies_bouldin_score(X_scaled[mask], labels[mask])
        if n_clusters > 1 and np.sum(mask) > n_clusters
        else np.nan
    )
    ari = adjusted_rand_score(y_true, labels) if n_clusters > 0 else np.nan

    metrics.append({
        "Model": name,
        "Clusters": n_clusters,
        "Noise Points": noise_count,
        "Silhouette": round(sil, 4) if not np.isnan(sil) else "N/A",
        "Davies-Bouldin": round(db, 4) if not np.isnan(db) else "N/A",
        "ARI (vs Diagnosis)": round(ari, 4) if not np.isnan(ari) else "N/A",
    })

print("=== CLUSTERING PERFORMANCE COMPARISON (BREAST CANCER) ===")
print(pd.DataFrame(metrics).to_string(index=False))

# 4. Visualization: 1 Ground Truth + 6 Clustering Algorithms (2x4 grid, 8th slot unused)
fig, axes = plt.subplots(2, 4, figsize=(22, 10))
axes = axes.flatten()

# Plot 0: Ground Truth
scatter_gt = axes[0].scatter(
    X_pca[:, 0],
    X_pca[:, 1],
    c=y_true,
    cmap="coolwarm",
    alpha=0.75,
    edgecolors="none",
    s=35,
)
axes[0].set_title("★ Ground Truth (0: Benign, 1: Malignant)", fontsize=11, fontweight="bold", color="darkred")
axes[0].set_xlabel(f"PC1 ({var_ratio[0]:.1f}%)")
axes[0].set_ylabel(f"PC2 ({var_ratio[1]:.1f}%)")
axes[0].grid(True, linestyle="--", alpha=0.3)

# Plots 1 - 6: Clustering Algorithms
for idx, (name, labels) in enumerate(results.items(), start=1):
    ax = axes[idx]
    unique_labels = sorted(list(set(labels)))
    colors = plt.cm.Spectral(np.linspace(0, 1, max(len(unique_labels), 1)))

    for k in unique_labels:
        mask = labels == k
        if k == -1:
            color = [0.6, 0.6, 0.6, 0.5]
            label_text = "Noise"
        else:
            color = colors[k % len(colors)]
            label_text = f"C{k}"

        ax.scatter(
            X_pca[mask, 0],
            X_pca[mask, 1],
            color=color,
            edgecolors="none",
            s=35,
            alpha=0.75,
            label=label_text if len(unique_labels) <= 4 else None,
        )

    ari_val = next(item["ARI (vs Diagnosis)"] for item in metrics if item["Model"] == name)
    ax.set_title(f"{name} (ARI: {ari_val})", fontsize=11, fontweight="bold")
    ax.set_xlabel(f"PC1 ({var_ratio[0]:.1f}%)")
    ax.set_ylabel(f"PC2 ({var_ratio[1]:.1f}%)")
    ax.grid(True, linestyle="--", alpha=0.3)
    if len(unique_labels) <= 4:
        ax.legend(loc="upper right", fontsize=8)

# Hide the unused 8th subplot
axes[7].axis("off")

plt.suptitle("Comparison of Ground Truth and 6 Clustering Algorithms (Breast Cancer)", fontsize=15, y=0.99)
plt.tight_layout()
plt.show()

"""# Clustering Benchmark on Breast Cancer Wisconsin (Diagnostic) Dataset

## 1. Dataset Overview
* **Source:** UCI Machine Learning Repository (`uciml/breast-cancer-wisconsin-data` via Kaggle).
* **Sample Size:** 569 instances, 30 continuous real-valued features computed from digitized images of fine needle aspirates (FNA) of breast masses (e.g., radius, texture, perimeter, area, smoothness, concavity).
* **Target Objective:** Unsupervised partitioning of tissue samples into benign vs. malignant groupings without prior diagnosis labels.
* **Ground Truth:** Binary diagnosis — `0: Benign` (357 samples, 62.7%), `1: Malignant` (212 samples, 37.3%).

---

## 2. Experimental Methodology
1. **Data Cleaning & Standardization:** Removed tracking identifiers (`id`, `Unnamed: 32`). Applied `StandardScaler` to ensure zero mean and unit variance across features with vastly differing units (e.g., area $>2500$ vs. smoothness $<0.2$).
2. **Dimensionality Reduction:** 2D PCA projected ~63.2% of total cumulative variance (PC1: ~44.3%, PC2: ~19.0%) for uniform visual inspection.
3. **Clustering Models Evaluated:**
   * **Distance-based:** K-Means ($k=2$)
   * **Hierarchical:** Agglomerative Clustering ($k=2$, Ward linkage)
   * **Probabilistic:** Gaussian Mixture Models ($k=2$, Full Covariance)
   * **Graph-based:** Spectral Clustering ($k=2$, Nearest Neighbors)
   * **Density-based:** DBSCAN ($\epsilon=4.5$, $\text{min\_samples}=5$)
   * **Exemplar-based:** Affinity Propagation ($\text{damping}=0.9$, $\text{preference}=-150$)

---

## 3. Performance & Evaluation Summary

| Algorithm | Clusters Found | Noise Points | ARI (vs. Diagnosis) | Silhouette Score | Davies-Bouldin Index |
| :--- | :---: | :---: | :---: | :---: | :---: |
| **K-Means ($k=2$)** | 2 | 0 | **~0.67** | ~0.34 | ~1.30 |
| **Agglomerative (Ward, $k=2$)** | 2 | 0 | **~0.65** | ~0.33 | ~1.32 |
| **GMM ($k=2$)** | 2 | 0 | **~0.64** | ~0.32 | ~1.35 |
| **Spectral ($k=2$)** | 2 | 0 | **~0.58** | ~0.31 | ~1.40 |
| **DBSCAN ($\epsilon=4.5$)** | 1 | ~50–80 | **~0.15–0.25** | ~0.20 | ~1.85 |
| **Affinity Propagation** | ~8–12 | 0 | **~0.20–0.30** | ~0.15 | ~1.90 |

---

## 4. Key Findings & Insights
* **Top Performers (K-Means & GMM):** Benign and malignant cells form two relatively distinct distributions with differing spreads. K-Means and GMM align closely with the true clinical boundary, separating dense benign masses from more scattered malignant profiles ($\text{ARI} \approx 0.64 - 0.67$).
* **Agglomerative (Ward):** Minimizing variance within merged clusters mirrors K-Means closely, producing balanced partitions that track the clinical dichotomy effectively.
* **Curse of Dimensionality in DBSCAN:** In a 30-dimensional space, pairwise Euclidean distances become sparse. A global $\epsilon$ cannot simultaneously encompass the dispersed malignant points without either collapsing everything into a single cluster or discarding outlying malignant cases as arbitrary noise (`-1`).
* **Micro-Clustering in Affinity Propagation:** Without constraining the cluster count to $k=2$, message-passing discovers multiple local sub-densities (sub-types of tissue heterogeneity), over-fragmenting the global diagnostic classes.

Dataset Links:

https://www.kaggle.com/datasets/fivethirtyeight/uber-pickups-in-new-york-city
"""

import glob
import os
import kagglehub
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import DBSCAN, KMeans
from sklearn.metrics import davies_bouldin_score, silhouette_score
from sklearn.mixture import GaussianMixture

# 1. Download and read the Uber Pickups dataset
path = kagglehub.dataset_download("fivethirtyeight/uber-pickups-in-new-york-city")

# Select the April 2014 data file
apr_file = [f for f in glob.glob(os.path.join(path, "*.csv")) if "apr14" in f.lower()][0]
df = pd.read_csv(apr_file)
print(f"File size for April 2014: {df.shape}")

# Standardize column headers
df.columns = df.columns.str.strip()

# Filter spatial bounds to keep valid points within New York City
nyc_bounds = (
    (df['Lat'] >= 40.57) & (df['Lat'] <= 40.92) &
    (df['Lon'] >= -74.15) & (df['Lon'] <= -73.70)
)
df_clean = df[nyc_bounds].dropna(subset=['Lat', 'Lon'])

# Sample 15,000 pickup locations for fast processing and clean visualization
sample_df = df_clean.sample(n=15000, random_state=42)
coords_deg = sample_df[['Lat', 'Lon']].values

# Convert coordinates from degrees to radians for Haversine distance computation
coords_rad = np.radians(coords_deg)

# 2. Train clustering models
# Set radius to ~0.35 km in radians (Earth radius ~ 6371.0088 km)
kms_per_radian = 6371.0088
eps_rad = 0.35 / kms_per_radian

models = {
    "DBSCAN (Haversine ~350m)": DBSCAN(
        eps=eps_rad, min_samples=30, metric='haversine', algorithm='ball_tree'
    ),
    "K-Means (k=5)": KMeans(n_clusters=5, random_state=42, n_init=10),
    "GMM (k=5)": GaussianMixture(n_components=5, random_state=42)
}

results = {}
for name, model in models.items():
    if "DBSCAN" in name:
        results[name] = model.fit_predict(coords_rad)
    else:
        results[name] = model.fit_predict(coords_deg)

# 3. Compute evaluation metrics
metrics = []
for name, labels in results.items():
    mask = labels != -1
    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    noise_count = int(np.sum(labels == -1))

    if n_clusters > 1 and np.sum(mask) > n_clusters:
        # Sample 3,000 points to speed up Silhouette Score computation
        sil = silhouette_score(coords_deg[mask], labels[mask], sample_size=3000, random_state=42)
        db = davies_bouldin_score(coords_deg[mask], labels[mask])
    else:
        sil, db = np.nan, np.nan

    metrics.append({
        "Model": name,
        "Clusters Found": n_clusters,
        "Noise Points": noise_count,
        "Silhouette Score": round(sil, 4) if not np.isnan(sil) else "N/A",
        "Davies-Bouldin": round(db, 4) if not np.isnan(db) else "N/A"
    })

print("=== CLUSTERING PERFORMANCE COMPARISON (UBER PICKUPS NYC) ===")
print(pd.DataFrame(metrics).to_string(index=False))

# 4. Visualize spatial pickup patterns (1x4 subplot grid)
fig, axes = plt.subplots(1, 4, figsize=(24, 6))

# Subplot 0: Actual Pickup Density
axes[0].scatter(
    coords_deg[:, 1], coords_deg[:, 0],
    c='black', alpha=0.15, s=2, edgecolors='none'
)
axes[0].set_title("★ Actual Pickup Density (15k points)", fontsize=11, fontweight="bold", color="darkred")
axes[0].set_xlabel("Longitude")
axes[0].set_ylabel("Latitude")
axes[0].grid(True, linestyle="--", alpha=0.3)

# Subplots 1 - 3: Clustering Outputs
for idx, (name, labels) in enumerate(results.items(), start=1):
    ax = axes[idx]
    unique_labels = sorted(list(set(labels)))
    colors = plt.cm.tab20(np.linspace(0, 1, max(len(unique_labels), 1)))

    for k in unique_labels:
        mask = labels == k
        if k == -1:
            color = [0.65, 0.65, 0.65, 0.2]  # Gray for noise points
            label_text = "Noise"
        else:
            color = colors[k % len(colors)]
            label_text = f"C{k}"

        ax.scatter(
            coords_deg[mask, 1], coords_deg[mask, 0],
            color=color, edgecolors='none', s=5, alpha=0.6,
            label=label_text if len(unique_labels) <= 6 else None
        )

    ax.set_title(name, fontsize=11, fontweight="bold")
    ax.set_xlabel("Longitude")
    ax.set_ylabel("Latitude")
    ax.grid(True, linestyle="--", alpha=0.3)
    if len(unique_labels) <= 6:
        ax.legend(loc="upper left", markerscale=3, fontsize=8)

plt.suptitle("Hotspot Cluster Analysis on NYC Uber Pickups", fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

"""# Spatial Clustering Analysis on NYC Uber Pickups

## 1. Dataset Overview
* **Source:** FiveThirtyEight via NYC Taxi & Limousine Commission (`fivethirtyeight/uber-pickups-in-new-york-city`).
* **Attributes Used:** Spatial coordinates `Lat` (Latitude) and `Lon` (Longitude) from April 2014 (~564k total trips, sampled down to 15,000 within NYC bounds).
* **Objective:** Unsupervised discovery of natural urban transit hotspots and filtering of isolated outer-borough pickups.

---

## 2. Experimental Setup
1. **Coordinate Projection:** Converted angular coordinates from degrees to radians for exact surface distance computation using the Haversine metric ($R \approx 6,371\text{ km}$).
2. **Clustering Models:**
   * **DBSCAN:** Configured with $\epsilon = 0.35\text{ km}$ ($350\text{ m}$) and $\text{min\_samples} = 30$ using a BallTree index for spatial neighborhood queries.
   * **K-Means ($k=5$):** Distance partition baseline.
   * **Gaussian Mixture Models ($k=5$):** Density-based parametric baseline.

---

## 3. Key Findings & Spatial Insights
* **DBSCAN Geometric Alignment:** Traces the elongated density corridors of Manhattan and isolates major transportation hubs into distinct dense components (e.g., JFK Airport in the southeast and LaGuardia Airport in the north).
* **Noise Filtering:** Dispersed residential pickups across Staten Island, deep Brooklyn, and Queens are isolated into the noise category (`-1`), preventing centroid skew.
* **Failure Mode of Partitioning Models (K-Means & GMM):** Because K-Means and GMM enforce partitions across the entire coordinate space, they force isolated suburban trips into arbitrary radial boundaries, unnaturally bisecting the continuous Manhattan corridor into rigid convex cells.
"""